In [ ]:
import cv2
import numpy as np
import string
import os

In [ ]:
#characters to ascii values and vice versa
ca={chr(i): i for i in range(255)}
ac={i:chr(i) for i in range(255)}

In [ ]:
print(ca)
print(ac)

{'\x00': 0, '\x01': 1, '\x02': 2, '\x03': 3, '\x04': 4, '\x05': 5, '\x06': 6, '\x07': 7, '\x08': 8, '\t': 9, '\n': 10, '\x0b': 11, '\x0c': 12, '\r': 13, '\x0e': 14, '\x0f': 15, '\x10': 16, '\x11': 17, '\x12': 18, '\x13': 19, '\x14': 20, '\x15': 21, '\x16': 22, '\x17': 23, '\x18': 24, '\x19': 25, '\x1a': 26, '\x1b': 27, '\x1c': 28, '\x1d': 29, '\x1e': 30, '\x1f': 31, ' ': 32, '!': 33, '"': 34, '#': 35, '$': 36, '%': 37, '&': 38, "'": 39, '(': 40, ')': 41, '*': 42, '+': 43, ',': 44, '-': 45, '.': 46, '/': 47, '0': 48, '1': 49, '2': 50, '3': 51, '4': 52, '5': 53, '6': 54, '7': 55, '8': 56, '9': 57, ':': 58, ';': 59, '<': 60, '=': 61, '>': 62, '?': 63, '@': 64, 'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90, '[': 91, '\\': 92, ']': 93, '^': 94, '_': 95, '`': 96, 'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101

In [ ]:
import urllib.request
#step 1:Image URL
url ="https://s.studiobinder.com/wp-content/uploads/2020/12/Best-iPhone-Camera-%E2%80%94-Top-Picks-with-Specs-Reviews-Prices-Featured.jpg"

#step 2:Load image from URL
response = urllib.request.urlopen(url)
image_array = np .asarray(bytearray(response.read()), dtype=np.uint8)
x=cv2.imdecode(image_array,cv2.IMREAD_COLOR)


In [ ]:
x

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
xrgb=cv2.cvtColor(x,cv2.COLOR_BGR2RGB)
xrgb

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
x.shape

(865, 1281, 3)

In [ ]:
xrgb.shape

(865, 1281, 3)

In [ ]:
key="123"
text="secret"

In [ ]:
text_ascii =[ca[ch] for ch in text]
key_ascii=[ca[ch] for ch in key]


In [ ]:
print(text,"=",text_ascii)
print(key,"=",key_ascii)

secret = [115, 101, 99, 114, 101, 116]
123 = [49, 50, 51]


In [ ]:
x_enc=x.copy()
n=0
m=0
z=0
l=len(text)
kl=0
for i in range(1):
  org_val=x_enc[n,m,z]
  new_val=text_ascii[1]^key_ascii[(1%3)]
  x_enc[n,m,z]=new_val
  print("original value is ",org_val," after performing XOR operation at pixel (",n,m,z,") i.e., ",text_ascii[i]," XOR ",key_ascii[i%3]," the new value is ",new_val)
  n=n+1
  m=m+1
  m=(m+1)%3
  z=(z+1)%3
  kl=(kl+1)%len(key)


original value is  255  after performing XOR operation at pixel ( 0 0 0 ) i.e.,  115  XOR  49  the new value is  87


In [ ]:
x_enc

array([[[ 87, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
n,m,z=0,0,0
kl=0
decrypt_msg=""
for i in range(1):
  value=x_enc[n,m,z]
  org_char=ac[value^key_ascii[i%3]]
  print("encrypted value is ",value,"after performing XOR operation for decryption at pixel(",n,m,z,") i.e.,",value,"XOR", key_ascii[i%3],"the new value is",ca[org_char])
  n=n+1
  m=m+1
  m=(m+1)%3
  z=(z+1)%3
  kl=(kl+1)%len(key)
  decrypt_msg=decrypt_msg+org_char
  print(decrypt_msg)


encrypted value is  87 after performing XOR operation for decryption at pixel( 0 0 0 ) i.e., 87 XOR 49 the new value is 102
f
